# Site settings
title: Du Nguyen
email: dunguyen90@gmail.com
description: The webpage of Du Nguyen. Hosted on Github Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dunguyen.github.io/website/" # the base hostname & protocol for your site
twitter_username: dunguyen90
github_username:  dunguyen
name: Du Nguyen
linkedin_username: dunguyen90


# Build settings
markdown: kramdown
