# Site settings
title: Du Nguyen
email: dunguyen90@gmail.com
description: The webpage of Du Nguyen. Hosted on Github Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dunguyen.dk/" # the base hostname & protocol for your site
images_folder: "https://dunguyen.dk/images/"
assets_folder: "https://dunguyen.dk/assets/"
enforce_ssl: "www.dunguyen.dk"
twitter_username: dunguyen90
github_username:  dunguyen
name: Du Nguyen
linkedin_username: dunguyen90


# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title.html
